

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'THOAI' at '12/3/15 5:54 PM' with Gradle 2.9
 *
 * @author THOAI, @date 12/3/15 5:54 PM
 */
public class so_nguyen_to {
	 static String result;
	
	 static check M = new check();
	public static String getResult() {
		return result;
	}
	public static void setResult(int N) {
		 
	     
	      if(M.kiemtrasonguyento(N)==0)
	      {
	    	  result="False";	    	
	      }
	      else
	      {
	    	  result="True";	    	 
	      }
	}
	
 }
    	  
  

